THIS SHOULD BE A LINTER ERRORproject:
  type: website
  output-dir: _site

website:
  title: "Nanobricks Wiki"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: quickstart.qmd
        text: Quickstart
      - href: tutorial.qmd
        text: Tutorial
      - href: sdk-guide.qmd
        text: SDK Guide
      - href: cookbook/index.qmd
        text: Cookbook
      - href: roadmap.qmd
        text: Roadmap
      - text: "More"
        menu:
          - href: production-examples.qmd
            text: Production Examples
          - href: comparison.qmd
            text: Framework Comparison
          - href: architecture-diagrams.qmd
            text: Architecture Diagrams
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Getting Started"
        contents:
          - index.qmd
          - quickstart.qmd
          - tutorial.qmd
          - task-system.qmd
          - task-reference.qmd
          - developer-workflows.qmd
          - distribution.qmd
      - section: "Cookbook"
        contents:
          - cookbook/index.qmd
          - cookbook/basic-pipeline.qmd
          - cookbook/dependency-injection.qmd
          - cookbook/error-handling.qmd
          - cookbook/testing-bricks.qmd
          - cookbook/composition-patterns.qmd
      - section: "Building Systems"
        contents:
          - sdk-guide.qmd
          - multi-project-development.qmd
          - production-examples.qmd
          - patterns.qmd
          - task-automation-guide.qmd
          - configuration.qmd
          - comparison.qmd
      - section: "Core Concepts"
        contents:
          - human.qmd
          - design-philosophy.qmd
          - principles.qmd
          - architecture.qmd
          - architecture-diagrams.qmd
          - type-safety.qmd
          - type-utilities.qmd
          - naming-conventions.qmd
      - section: "Advanced Topics"
        contents:
          - ai-integration.qmd
          - ai-protocols.qmd
          - superpowers.qmd
      - section: "Evolution"
        contents:
          - project-history.qmd
          - evolution.qmd
          - v1/concept.qmd
          - v2/evolved-concept.qmd
          - roadmap.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: false
    code-tools: true