[package]
name = "text-processor"
version = "1.1.0"
description = "A powerful text processing nanobrick (improved)"
author = "Alice Developer"
license = "MIT"
keywords = [ "text", "processing", "nlp",]
classifiers = []
python_requires = ">=3.13"
created_at = "2025-05-28T11:24:53.210269"
updated_at = "2025-05-28T11:24:53.210269"
brick_class = "__main__.TextProcessor"
skills = []

[package.dependencies]
