project:
  type: website
  output-dir: _site

website:
  title: "Nanobrick Docs"
  favicon: favicon.svg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: quickstart.qmd
        text: Quickstart
      - href: tutorial.qmd
        text: Tutorial
      - href: sdk-guide.qmd
        text: SDK Guide
      - href: cookbook/index.qmd
        text: Cookbook
      - href: roadmap.qmd
        text: Roadmap
      - text: "More"
        menu:
          - href: production-examples.qmd
            text: Production Examples
          - href: comparison.qmd
            text: Framework Comparison
          - href: architecture-diagrams.qmd
            text: Architecture Diagrams
  sidebar:
    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - section: "Getting Started"
        contents:
          - index.qmd
          - quickstart.qmd
          - tutorial.qmd
          - section: "Task System"
            contents:
              - task-overview.qmd
              - task-system.qmd
              - task-reference.qmd
              - task-automation-guide.qmd
          - section: "Development Setup"
            contents:
              - developer-workflows.qmd
              - distribution.qmd
      - section: "Core Concepts"
        contents:
          - human.qmd
          - nanobrick.qmd
          - pipeline.qmd
          - section: "Architecture & Design"
            contents:
              - architecture.qmd
              - architecture-diagrams.qmd
              - design-philosophy.qmd
              - principles.qmd
          - section: "Type System"
            contents:
              - type-safety.qmd
              - type-utilities.qmd
          - naming-conventions.qmd
      - section: "Building Systems"
        contents:
          - sdk-guide.qmd
          - patterns.qmd
          - section: "Deployment & Production"
            contents:
              - multi-project-development.qmd
              - production-examples.qmd
              - configuration.qmd
          - comparison.qmd
      - section: "Cookbook"
        contents:
          - cookbook/index.qmd
          - section: "Basic Patterns"
            contents:
              - cookbook/basic-pipeline.qmd
              - cookbook/dependency-injection.qmd
          - section: "Advanced Patterns"
            contents:
              - cookbook/error-handling.qmd
              - cookbook/testing-bricks.qmd
              - cookbook/composition-patterns.qmd
      - section: "Advanced Topics"
        contents:
          - superpowers.qmd
          - section: "AI Integration"
            contents:
              - ai-integration.qmd
              - ai-protocols.qmd
      - section: "Agentic Documentation"
        contents:
          - agentic-docs-overview.qmd
          - agentic-docs-guide.qmd
          - agentic-docs-walkthrough.qmd
          - agentic-docs-formats.qmd
          - agentic-workflows-guide.qmd
          - agentic-cheatsheet.qmd
      - section: "Evolution"
        contents:
          - roadmap.qmd
          - section: "Concept Evolution"
            contents:
              - evolution.qmd
              - project-history.qmd
              - v1/concept.qmd
              - v2/evolved-concept.qmd
      - section: "Claude Code"
        contents:
          - claude-code.qmd
      - section: "Git Cheat Sheet"
        contents:
          - git-cheat-sheet.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: false
    code-tools: true