project:
  type: website
  output-dir: _site

website:
  title: "Nanobricks Wiki"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: quickstart.qmd
        text: Quickstart
      - href: tutorial.qmd
        text: Tutorial
      - href: sdk-guide.qmd
        text: SDK Guide
      - text: "More"
        menu:
          - href: production-examples.qmd
            text: Production Examples
          - href: comparison.qmd
            text: Framework Comparison
          - href: architecture-diagrams.qmd
            text: Architecture Diagrams
          - href: roadmap.qmd
            text: Roadmap
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Getting Started"
        contents:
          - index.qmd
          - quickstart.qmd
          - tutorial.qmd
      - section: "Building Systems"
        contents:
          - sdk-guide.qmd
          - production-examples.qmd
          - patterns.qmd
          - configuration.qmd
          - comparison.qmd
      - section: "Core Concepts"
        contents:
          - human.qmd
          - principles.qmd
          - architecture.qmd
          - architecture-diagrams.qmd
          - type-safety.qmd
          - naming-conventions.qmd
      - section: "Advanced Topics"
        contents:
          - ai-integration.qmd
          - ai-protocols.qmd
          - superpowers.qmd
      - section: "Evolution"
        contents:
          - evolution.qmd
          - v1/concept.qmd
          - v2/evolved-concept.qmd
          - roadmap.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: false
    code-tools: true